# This is a basic workflow to help you get started with Actions

name: Github Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v2
    -
      name: build site
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        target_branch: gh-pages
        build_dir: /
        repo: ThatGeekyWeeb/rewrite-squidtify.git
        committer: Mia <thatgeekyweeb@gmail.com>
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
